# Generated by Django 2.0.1 on 2018-02-05 00:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Student Unique ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter your first name.', max_length=200)),
                ('last_name', models.CharField(help_text='Enter your last name.', max_length=200)),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Student Unique ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter your first name.', max_length=200)),
                ('last_name', models.CharField(help_text='Enter your last name.', max_length=200)),
                ('progress', models.IntegerField()),
                ('student', models.ManyToManyField(help_text='Select student name.', to='Dashboard.Student')),
            ],
        ),
    ]
