# Generated by Django 2.0.2 on 2018-02-21 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Class Unique ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a classroom name.', max_length=200)),
                ('student', models.ManyToManyField(help_text='Select student name.', to='Dashboard.Student')),
            ],
        ),
    ]
