# Generated by Django 2.0.3 on 2018-04-16 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0002_auto_20180221_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(help_text='True or False: Malaria is bad', max_length=200)),
                ('question2', models.CharField(help_text='Enter your last name.', max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='class',
            old_name='student',
            new_name='students',
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Teacher Unique ID', primary_key=True, serialize=False),
        ),
    ]
