# Generated by Django 2.0.3 on 2018-04-17 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_class_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='target_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(default='6K9BwT', max_length=6),
        ),
    ]
